```javascript
var checkPromise = new Promise((resolve, reject) => {
    reject(Error('Fail statement'))
});

checkPromise.catch(error => console.log(error.message))
checkPromise.catch(error => console.log(error.message))
```
//////////////////////////////////////////////////////////////

```javascript
var checkPromiseAgain = new Promise((resolve, reject) => {
    return Promise.reject(Error('Fail statement'))
});

checkPromiseAgain.catch(error => console.log(error.message))
checkPromiseAgain.catch(error => console.log(error.message))
```

///////////////////////////////////////////////////////////////

```javascript
var p = new Promise((resolve, reject) => {
    reject(Error('The Fails!'))
})
    .catch(error => console.log(error))
    .then(error => console.log(error))

```
/////////////////////////////////////////////////////////////////

```javascript
Promise.resolve('Success')
.then(data => {
    data.toUpperCase()
  })
.then(data => console.log(data))
```